Travisで落ちているので、nokogiriのインストールを消してみた
Fetching: nokogiri-1.7.1.gem (100%)
ERROR:  Error installing nokogiri:
nokogiri requires Ruby version >= 2.1.0.
The command "gem install nokogiri -- --with-cflags='--std=gnu99'" failed and exited with 1 during .